# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y%m%d'),
        ),
    ]
