# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_update',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
