# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0003_auto_20170120_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessityRequestDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TextMissing.Document')),
            ],
            bases=('TextMissing.document',),
        ),
        migrations.CreateModel(
            name='RectorDispositionDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TextMissing.Document')),
            ],
            bases=('TextMissing.document',),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TextMissing.Document')),
            ],
            bases=('TextMissing.document',),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('rector disposition', 'Rector disposition'), ('necessity request', 'Necessity request')], default='uploaded', max_length=20),
        ),
    ]
