# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0004_auto_20170120_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(default=0.1, max_length=64),
        ),
    ]
