# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0005_auto_20170120_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.FloatField(default=0.1),
        ),
    ]
