# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextMissing', '0006_auto_20170120_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(default=0.1, max_length=64),
        ),
    ]
