# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_usergroup'),
        ('TextMissing', '0007_auto_20170120_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flow_type', models.CharField(choices=[('rector disposition', 'Rector Disposition'), ('necessity request', 'Necessity Request')], max_length=30)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('state', models.PositiveIntegerField(default=0)),
                ('initiator', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LoginApp.Client')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='flow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='TextMissing.DocumentFlow'),
        ),
    ]
