# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0007_auto_20170121_1539'),
        ('TextMissing', '0009_auto_20170121_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=64)),
                ('size', models.FloatField(default=0)),
                ('version', models.CharField(default=0.1, max_length=64)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('abstract', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y%m%d')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LoginApp.Client')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='TextMissing.Document')),
            ],
        ),
    ]
