# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_auto_20170121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='LoginApp.GroupType'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(null=True, related_name='Users', to='LoginApp.Client'),
        ),
    ]
