# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0006_auto_20170121_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(related_name='Users', to='LoginApp.Client'),
        ),
    ]
